### PR TITLE
skip If Force INDEX

### LINKED ISSUE #671: sql语句不支持 强制索引 force index（xxx）
sql语句不支持 强制索引 force index（xxx） ,我在分库分表的逻辑sql语句中加入强制索引后，sql路由会出现问题，这个不应该啊

### PR DESCRIPTION
**Pull request by saaavsaaa**
Fixes #671 .

Changes proposed in this pull request:
-TableReferencesClauseParser.java
-LexerEngine.java
-

### CODE REVIEW

**Comment by terrymanu** [comment]
Code review suggestion:

1. I want make sure why did not use original `String skipParentheses(final SQLStatement sqlStatement)` for this case. I think it is ok for this case. Is it nessesary to add a new method `public void skipParentheses()` here?

2.   Please add a test case for this. You can add sql test case on `sharding-jdbc/sharding-jdbc/sharding-sql-test/src/main/resources/sql/dql/select.xml`, and add parse context assert on `sharding-jdbc/sharding-jdbc/sharding-core/src/test/resources/parser/select.xml`. Test cases is really important to prove your change is correct.

**Comment by terrymanu** [comment]
More code review suggestions:

I consider for this pull request carefully, the pr is `incorrect` now. 

Please note sharding-jdbc has a concept for logic index, use force index should add a index token in parser module, and rewrite index token to real index name on rewrite module.

Please reference `AbstractCreateParser` and `SQLRewriteEngine`

**Comment by saaavsaaa** [comment]
OK.I will get to know the concept for logic index first.

**Comment by saaavsaaa** [comment]
I close it until I do it well.

**Comment by saaavsaaa** [comment]
Without Unit Test. And I'm doing it.Any suggestions？

**Comment by terrymanu** [comment]
Thank you for contribute, some suggestions:

1. for code `this.lexerEngine`, just remove `this.`, we use `lexerEngine` directly in the normal.

2. instead `lexerEngine.skipIfEqual(new TokenType[]{MySQLKeyword.FORCE}` to `lexerEngine.skipIfEqual(MySQLKeyword.FORCE)`, we use Varargs here. Same as `lexerEngine.skipIfEqual(new TokenType[]{MySQLKeyword.INDEX}`

3. you can inline `if (skipIfForce) {`, just like `if (lexerEngine.skipIfEqual(MySQLKeyword.FORCE) && lexerEngine.skipIfEqual(MySQLKeyword.INDEX)) {`

4. remove unnecessary empty line for `TableReferencesClauseParser` line 141.

5. `isLogicIndex` methdo on class ShardingRule, maybe can simplify, like:

```java
public boolean isLogicIndex(final String logicIndexName, final String logicTableName) {
    return logicIndexName.equals(getTableRule(logicTableName).getLogicIndex());
}
```

That's it. After finish test case, i will merge it. Thank you.

**Comment by terrymanu** [comment]
I resolve conflict for it, but test case cannot pass. please fix test case first.

**Comment by saaavsaaa** [comment]
It should be fine.
shardingjdbc/sharding-jdbc/sharding-core/src/test/resources/parser/select.xml 
parser-result id -> sql-case-id

**Pull request merged**
